// Asserts which DealCourt app controls appear per deal state and role (run: node app/check-actions.mjs app/index.html).
import { readFileSync } from "node:fs";
const html = readFileSync(process.argv[2], "utf8");
const js = html.match(/<script type="module">([\s\S]*?)<\/script>/)[1];
const body = js.slice(js.indexOf("const urlField"), js.indexOf("async function show"));
const esc = (s) => String(s ?? "");
const gen = (w, d = 4) => (Number(w) / 1e18).toFixed(d).replace(/\.?0+$/, "");
const pct = (b) => b / 100 + "%", when = () => "T";
const make = new Function("esc", "gen", "pct", "when", "ctx", `let me = ctx.me; ${body}; return { actions, filings };`);
const C = "0xc", P = "0xp", now = Date.now() / 1000, past = now - 100, fut = now + 9999;
const base = { client: C, provider: P, amount: "10000000000000000", delivery_deadline: fut, review_deadline: fut, evidence_deadline: fut, appeal_deadline: fut, provider_share_bps: 0, appealed: false };
const run = (me, d, ev = {}, props = { client: -1, provider: -1 }) => make(esc, gen, pct, when, { me }).actions({ ...base, ...d }, ev, props);
const has = (h, s) => h.includes(s);
const check = (name, ok) => { if (!ok) { console.log("FAIL", name); process.exitCode = 1; } else console.log("ok  ", name); };

check("no wallet: prompt only", has(run(null, { status: "DELIVERED" }), "Connect the client"));
check("outsider: no actions", has(run("0xz", { status: "DELIVERED" }), "not a party"));
check("proposed/provider: accept", has(run(P, { status: "PROPOSED" }), 'data-act="accept_deal"'));
check("proposed/client: withdraw + reclaim disabled before deadline", has(run(C, { status: "PROPOSED" }), "withdraw_proposal") && /reclaim_undelivered"[^>]*disabled/.test(run(C, { status: "PROPOSED" })));
check("active/client after deadline: reclaim enabled", /reclaim_undelivered"(?![^>]*disabled)/.test(run(C, { status: "ACTIVE", delivery_deadline: past })));
check("active/provider: deliver form", has(run(P, { status: "ACTIVE" }), 'data-form="deliver"'));
const dlv = run(C, { status: "DELIVERED" });
check("delivered/client: approve + dispute with evidence URLs", has(dlv, '"approve"') && has(dlv, 'data-form="open_dispute"') && has(dlv, 'name="uris"'));
check("delivered: mutual settlement form", has(dlv, 'data-form="propose_settlement"'));
check("delivered after review: release", has(run(P, { status: "DELIVERED", review_deadline: past }), "release_after_review"));
const d1 = run(C, { status: "DISPUTED" }, { client: { statement: "x", uris: [] } });
check("disputed, provider not filed, window open: adjudicate disabled", /data-act="adjudicate"[^>]*disabled/.test(d1));
const d2 = run(C, { status: "DISPUTED" }, { client: {}, provider: {} });
check("disputed, both filed: adjudicate enabled", /data-act="adjudicate"(?![^>]*disabled)/.test(d2));
const d3 = run(C, { status: "DISPUTED", evidence_deadline: past }, { client: {} });
check("disputed, deadline passed: adjudicate enabled", /data-act="adjudicate"(?![^>]*disabled)/.test(d3));
const d4 = run(P, { status: "DISPUTED" }, { client: {} });
check("disputed/provider: evidence form with URLs", has(d4, 'data-form="submit_evidence"') && has(d4, 'name="uris"'));
check("disputed/provider already filed: no evidence form", !has(run(P, { status: "DISPUTED" }, { client: {}, provider: {} }), "submit_evidence"));
const r70p = run(P, { status: "RULED", provider_share_bps: 7000 }), r70c = run(C, { status: "RULED", provider_share_bps: 7000 });
check("ruled 70% to provider: provider cannot appeal", !has(r70p, 'data-form="appeal"') && has(r70p, "smaller share"));
check("ruled 70% to provider: client can appeal with bond", has(r70c, 'data-form="appeal"') && has(r70c, 'name="bond"') && has(r70c, 'name="uris"'));
check("ruled 50/50: both can appeal", has(run(P, { status: "RULED", provider_share_bps: 5000 }), 'data-form="appeal"') && has(run(C, { status: "RULED", provider_share_bps: 5000 }), 'data-form="appeal"'));
check("ruled, appealed: no appeal form", !has(run(C, { status: "RULED", provider_share_bps: 7000, appealed: true }), 'data-form="appeal"'));
check("ruled before window ends: finalize disabled", /finalize_ruling"[^>]*disabled/.test(r70c));
check("ruled after window: finalize enabled", /finalize_ruling"(?![^>]*disabled)/.test(run(C, { status: "RULED", provider_share_bps: 7000, appeal_deadline: past })));
check("settled: no actions", run(C, { status: "SETTLED" }) === "");
